### ISSUE TITLE
CSS still overriding styles in webapplications

### ISSUE THREAD

**Issue by thongsav-usgs** [USGS-R/repgen#33]
.main-container rule of https://github.com/USGS-R/repgen/blob/master/inst/extdata/styles.css is overriding a bootstrap rule in the AQCU applicatoin.

Can you namespace this class? eg: .repgen-main-container

**Comment by jordansread** [comment]
@thongsav-usgs I must not have committed that. I thought I fixed it locally, and will check on that.
