### ISSUE TITLE
Fix package check NOTEs and WARNINGS

### ISSUE THREAD

**Issue by jordansread** [USGS-R/repgen#45]
Should be able to see when running `check` from RStudio

**Comment by jordansread** [comment]
@mhines-usgs interested?

**Comment by mhines-usgs** [comment]
From Travis CI
- [x] Undocumented code objects: ‘getSimsUrl’ ‘json’ ‘startUvhydrographRender’ ‘uvhydrographPlot’
  All user-level objects in a package should have documentation entries. See chapter ‘Writing R documentation files’ in the ‘Writing R Extensions’ manual.
- [ ] checking examples ... ERROR
  Running examples in ‘repgen-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > 
  > ### Name: sensorreadingsummary
  > 
  > ### Title: sensorreadingsummary report
  > 
  > ### Aliases: sensorreadingsummary
  > 
  > ### sensorreadingsummary,character,character-method
  > 
  > ### sensorreadingsummary,list,character-method
  > 
  > ### sensorreadingsummary,list,missing-method
- [ ] Error in (function (toc = FALSE, toc_depth = 2, number_sections = FALSE,  : 
  unused argument (self_contained = FALSE)
  Calls: sensorreadingsummary ... render -> create_output_format -> do.call -> <Anonymous>
  Execution halted
- checking for unstated dependencies in ‘tests’ ... OK
- checking tests ...
  Running ‘testthat.R’ [31s/31s]
  ERROR
  Running the tests in ‘tests/testthat.R’ failed.
  Last 13 lines of output:
           pandoc = pandoc_options(to = "latex", from = from_rmarkdown(fig_caption, 
               md_extensions), args = args, keep_tex = keep_tex), clean_supporting = !keep_tex, 
           pre_processor = pre_processor, intermediates_generator = intermediates_generator)
   })(self_contained = FALSE)

**This error has to do with the newer rmarkdown package. Travis CI uses .8.1 or so and we are still using .6.1 -- when I upgrade locally to that version, I encounter the same message.**
- [ ]  testthat results ================================================================
  OK: 9 SKIPPED: 0 FAILED: 2
  1. Error: example data vdiagram 
  2. Error: examples work 
  
  Error: testthat unit tests failed

**Comment by mhines-usgs** [comment]
From my local check:
- [x] checking installed package size ... NOTE
  installed size is 56.6Mb
  sub-directories of 1Mb or more:
    extdata  56.3Mb
- [x] \* checking dependencies in R code ... NOTE
  Namespace in Imports field not imported from: 'methods'
  All declared Imports should be used.
- [x] ':::' call which should be '::': 'gsplot:::ylim'
  See the note in ?`:::` about the use of this operator.
- [ ]  checking R code for possible problems ... NOTE
  Setting endpoint to  https://cida-test.er.usgs.gov/auth-webservice/

**Comment by mhines-usgs** [comment]
http://www.ats.ucla.edu/stat/r/faq/referencing_objects.htm

**Comment by jordansread** [comment]
note for the `:::`, `ylim` is now a function in `gsplot` that is exported, so `:::` shouldn't be necessary. 
I think you can ignore the first NOTE, since this package isn't going to CRAN, but wow, that is a big chunk of data for a package. Hopefully it doesn't get in the way of installations.

**Comment by mhines-usgs** [comment]
@jread-usgs thanks, that did get rid of one more note :)!

**Comment by mhines-usgs** [comment]
The size issue might just be my local copy... I can weed it out and see. It's from the example datasets.
