### ISSUE TITLE
vdiagram paging function loses _output.yaml

### ISSUE THREAD

**Issue by jordansread** [USGS-R/repgen#78]
the reason _output.yaml doesn't come into play for the reports is because  the paging function moves the Rmds up one directory, so they are no longer in the same dir as _output.yaml

@thongsav-usgs I am guessing there was a reason for this change? Permissions to `pagingVdiagram(system.file('vdiagram', package = 'repgen')`?

**Comment by jiwalker-usgs** [comment]
@jread-usgs Mike was having problems because the scripts were trying to write to directories they didn't have permission to write to.  All of the work should take place in the workdir that is set up which should be getwd() instead of system.file()

**Comment by jordansread** [comment]
ok, that makes sense. We should figure out how we are dealing with the report-specific params. I don't think it makes sense to move around `_output.yaml`, but we could have a config reader or something like that.
